### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by ysreenivasulu**
java-2

### CODE REVIEW

**Comment by ysreenivasulu** [comment]
hi sreenu -2 
i have written java program please this review program
Thank you 
ysreenu-1

**Comment by ysreenivasulu2** [comment]
hi sreeenu-1
i have verify the code but add for loop method

Thank you 
ysreenu-2

**Comment by ysreenivasulu** [comment]
Hi ysreenu-2
I have added for loop method and please review my code
Thank you 
ysreenu-1

**Review by ysreenivasulu2 — COMMENTED** [review]
ok thank you sir

**Pull request merged**
